name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      keyworddemo: "macnicademo"
      secretworddemo: ${{ secrets.Name }}
      image: "my-image:"$(date +%s)
      USER: ${{ secrets.user }}
      TOKEN: ${{ secrets.token }}  
steps:
    - uses: actions/checkout@v1
    - name: Demo to use Secret env vars
      run: |
        echo ${secretworddemo}
        echo ${keyworddemo}

    - name: Build the Docker image
      run: |
        docker build --tag ${image} .
      
    - name: Login to Docker Hub
      run: |
        docker login --username ${USER} --password ${TOKEN} "https://index.docker.io/v1/"
      
    - name: Publish Image
      run: docker push ${image}
