name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      keyworddemo: "macnicademo"
      secretworddemo: ${{ secrets.Name }}
      tag: `$(date +%s)`
      image: "myimage"
      USER: ${{ secrets.user }}
      TOKEN: ${{ secrets.token }}  

    steps:
    - uses: actions/checkout@v2
    - name: Demo to use Secret env vars
      run: |
        echo ${secretworddemo}
        echo ${keyworddemo}
        echo ${tag}

    - name: Build the Docker image
      run: |
        docker build --tag ${image}:${tag} .
      
    - name: Login to Docker Hub
      run: |
        docker login --username ${USER} --password ${TOKEN} "https://index.docker.io/v1/"
      
    - name: Publish Image
      run: docker push ${image}:${tag}
