name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Demo to use Secret env vars
      run: |
        echo ${secretworddemo}
        echo ${keyworddemo}
      env:
        keyworddemo: macnicademo
        secretworddemo: ${{ secrets.Name }}
        tag: $(date +%s)

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:${tag}
      
    - name: Login to Docker Hub
      run: |
        docker login --username ${USER} --password ${TOKEN} "https://index.docker.io/v1/"
      env:
        USER: ${{ secrets.user }}
        TOKEN: ${{ secrets.token }}  
    - name: Publish Image
      run: docker push my-image-name:${tag}
